### ISSUE TITLE
alchemical_introduction.ipynb: 2.3 visualising solvated merged molecules

### ISSUE THREAD

**Issue by jmichel80** [michellab/bssccpbiosim2022#9] opened 2022-09-12 08:30 UTC
In [section 2.3 of the intro notebook](https://github.com/michellab/bssccpbiosim2022/blob/main/introduction_to_alchemistry/alchemical_introduction.ipynb) for learning purposes it would be good for delegates to visuliase the state of the system they assembled after solvation. 

However visualising the solvated system with 

```
solvated = BSS.Solvent.tip3p(molecule=merged, box=3*[40*BSS.Units.Length.angstrom])
BSS.Notebook.View(solvated).system()
```

doesn't show the merged molecule. 

![image](https://user-images.githubusercontent.com/11722212/189607498-301f6b13-3093-4eb1-9e73-e403500a9846.png)

Earlier visualisations of solutes loaded from PDB do work (section 1.1. of notebook)

**Comment by lohedges** [comment] 2022-09-12 08:52
The issue is that you are writing an intermediate PDB file for NGLView using inconsistent propertly names. The water molecules have things like `coordinates`, `element`, etc., whereas those in the merged molecules have property names with an additional suffix `0` or `1` to specify the end state, e.g. `coordinates0`. This means that the merged molecule isn't being written to file properly.

If you want to view the merged molecule, then you'll need to convert to one of the end states, e.g.:

```python
lam0 = merged._toRegularMolecule()
lam1 = merged._toRegualrMolecule(is_lambda1=True)
```

You could then combine this with the solvent to view.

For the purposes of visualisation, I could modify the `View` class to do this internally. always convert to one of the end states (perhaps specified by an option) when a merged molecule is detected. Let me know if this would be useful. I've also realised that the `View` class doesn't let you specify a property map (unlike most other functionality) so you wouldn't be able to remap properties anyway. (Meaning you'd need to manually reconstruct the system before creating the view, as I suggest above.)

**Comment by jmichel80** [comment] 2022-09-12 09:00
I think it would be useful to hide these details from the users of BSS.Notebook . We could by default map merged molecules to lambda0 and use a keyword arg to control this setting. This would also help understand the visualisation of the mappings.

**Comment by lohedges** [comment] 2022-09-12 09:05
No problem, I'll try to add this later today when I get a chance. In the old workshops we just used `._toRegularMolecule()` to view the end states, but now have the nicer `viewMapping` functionality built in. I agree that it would be good to have general support for merged molecules in the viewer in case the user wants to visualise it as part of a larger system, e.g. with solvent.

**Comment by annamherz** [comment] 2022-09-12 12:04
> but now have the nicer `viewMapping` functionality built in.

yep this is really nice and we have it earlier in the notebook!

> No problem, I'll try to add this later today when I get a chance.

Thank you! I'll adjust the notebook once the support is added for the viewer 😊

**Comment by lohedges** [comment] 2022-09-12 13:31
Okay, I've added some functionality that reconstructs a chosen end state of a perturbable system behind the scenes. This allows you to view perturbable molecules, or systems containing them, directly, i.e. without first needing to extract the end state.

I've tested locally and it works for me (although in this case you can't really see anything without first hiding the solvent with `not water` in the selection box). Let me know if you find other issues.

Cheers.

**Closed as completed** 2022-09-13 10:39 UTC
